[build]
target = "xtensa-esp32-espidf"

[target.xtensa-esp32-espidf]
linker = "ldproxy"
# runner = "espflash --monitor" # Select this runner for espflash v1.x.x
# runner = "espflash flash --monitor" # Select this runner for espflash v2.x.x
runner = "espflash flash -M -p /dev/ttyACM0 -f 80mhz -m dio"
rustflags = ["--cfg", "espidf_time64", "--cfg", "crossbeam_no_atomic_64", "--cfg", "tokio_unstable", "--cfg", "mio_unsupported_force_poll_poll"] # Extending time_t for ESP IDF 5: https://github.com/esp-rs/rust/issues/110

[unstable]
build-std = ["std", "panic_abort"]

[env]
MCU="esp32"
# Note: this variable is not used by the pio builder (`cargo build --features pio`)
ESP_IDF_VERSION = "v5.1.2"